server:
  port: 8080

spring:
  config:
    import:
      - classpath:config-mybatis.yml
      - classpath:config-db.yml
      - classpath:config-liquibase.yml
  application:
    name: NexHubStudio-backend

  # JPA Configuration
  # Security Configuration (기본 비활성화)
  security:
    user:
      name: admin
      password: admin
  liquibase:
    clear-checksums: true

# JWT Configuration
jwt:
  secret: NexHubStudioSecretKeyForJWTTokenGeneration2024
  expiration: 86400000 # 24 hours in milliseconds

