spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
    drop-first: false
    default-schema: public
    contexts: development, production
    parameters:
      liquibase.schema: public
      app.name: NexHubStudio-backend
    clear-checksums: true
